

export default function Error() {
    return (
      <div>
         <div className="min-h-screen flex items-center justify-center bg-blue-100">
        <div className="max-w-md bg-white p-6 rounded shadow-lg">
          <h2 className="text-orange-500 font-bold text-2xl mb-2">404</h2>
          <h1 className="text-gray-600 font-light text-xl mb-4">Page Not Found</h1>
          <p className="text-gray-700 mb-4">
            The specified file was not found on this website. Please check the
            URL for mistakes and try again.
          </p>
          <h3 className="text-gray-700 font-bold text-sm mb-2">
            Why am I seeing this?
          </h3>
          <p className="text-gray-700 mb-4">
            This page was generated by the Firebase Command-Line Interface. To
            modify it, edit the <code>404.html</code> file in your projects
            configured <code>public</code> directory.
          </p>
        </div>
      </div>
      </div>
    )
  }
  